# Generated by Django 3.0 on 2019-12-07 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentType', models.CharField(max_length=200)),
                ('incidentTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('details', models.TextField(blank=True, null=True)),
                ('photoPath', models.FilePathField()),
                ('timeSubmitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('userID', models.CharField(max_length=200)),
            ],
        ),
    ]
