# Generated by Django 3.0 on 2019-12-10 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incidentDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incidentTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incidentType',
            field=models.CharField(choices=[('Littering', 'Littering'), ('Loitering', 'Loitering'), ('Graffiti', 'Graffiti'), ('Speeding', 'Speeding'), ('Parking', 'Parking')], max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='photoPath',
            field=models.FilePathField(path='/home/oem/Documents/Other/PoliceHackathon/CRITr/uploads'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
